version: '3'
services:
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    expose:
      - "3002" 
  apirest:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api/routes:/app/routes 
      - ./api/index.js:/app/index.js
      - ./api/package.json:/app/package.json
    environment:
      - WORKER_HOST=worker
      - WORKER_PORT=3002
    depends_on:
      - worker

  site:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ./app
    volumes: 
      - ./app/public:/app/public
      - ./app/views:/app/views
      - ./app/package.json:/app/package.json

  nginx:
    depends_on: 
      - site
      - apirest
      - worker
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"